name: dias_de_pesca
description: "App de sugestao de melhores dias para pesca baseado nas fases da lua."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # Navegacao e injecao de dependencias
  flutter_modular: ^6.3.4

  # Gerenciamento de estado
  mobx: ^2.3.3
  flutter_mobx: ^2.2.1
  
  font_awesome_flutter: ^11.0.0
  json_annotation: ^4.9.0
  http: ^1.3.0
  objectbox: ^5.3.2
  objectbox_flutter_libs: ^5.3.2
  geolocator: ^11.0.0
  flutter_svg: ^2.0.17
  fl_chart: ^0.68.0
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

  # Code generation para MobX
  build_runner: ^2.4.13
  mobx_codegen: ^2.6.1
  json_serializable: ^6.8.0
  objectbox_generator: ^5.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/
